title: Precision Medicine Symposium

description: > # this means to ignore newlines until "baseurl:"
  Precision Medicine Initiative (PMI) Symposium happening at the University of Central Florida. Hosted by the Center for Entrepreneurial Leadership.

baseurl: '/pmi'
url: "http://opsbug.com"

# Build settings
markdown: kramdown